services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=istasyon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Istanbul
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nocodb:
    image: nocodb/nocodb
    environment:
      - SERVICE_URL_NOCODB_8080
    volumes:
      - 'nocodb-data:/usr/app/data/'
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '--spider'
        - 'http://127.0.0.1:8080/api/v1/health'
      interval: 5s
      timeout: 20s
      retries: 10
    ports:
      - '8089:8080'
    depends_on:
      - db

volumes:
  postgres_data_dev:
