services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=istasyon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Istanbul
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - istasyon_network
    container_name: istasyon-db

  nocodb:
    image: nocodb/nocodb:latest
    container_name: istasyon-nocodb
    environment:
      - NC_DB=pg://istasyon-db:5432?u=postgres&p=postgres&d=istasyon
    ports:
      - "8080:8080"
    volumes:
      - nocodb_data:/usr/app/data/
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - istasyon_network

volumes:
  postgres_data_dev:
  nocodb_data:


networks:
  istasyon_network:
    driver: bridge
