services:
  backend:
    build:
      context: ./backend/IstasyonDemo.Api
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      # Host kısmına Coolify'daki veritabanının internal adını yazdık
      - ConnectionStrings__DefaultConnection=Host=fs4kwcgwcos48ssw0w48sssw;Database=postgres;Username=postgres;Password=${POSTGRES_PASSWORD};TrustServerCertificate=True
      - AllowedOrigins__0=https://istasyon.tiginteknoloji.tr
      - AllowedOrigins__1=https://istasyonapi.tiginteknoloji.tr
      - JwtSettings__SecretKey=${JWT_SECRET}
      - TZ=Europe/Istanbul
    networks:
      - coolify
    volumes:
      - backend_backups:/app/Backups

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Europe/Istanbul
    networks:
      - coolify
    depends_on:
      - backend

networks:
  coolify:
    external: true
